"""
sv_file.py — SystemVerilog file structure for grouper.sv.

Responsible for:
  - File header (auto-generation notice, description, bind example)
  - Package import
  - Module declaration
  - Variable declarations (one per BlockConfig)
  - Assign blocks (delegated to generator.emit_block)
  - endmodule footer

Only call build_sv_file() from main.py. Everything else here is internal.
"""

from datetime import date

from config import BlockConfig
from generator import emit_block


# ---------------------------------------------------------------------------
# Column widths for declaration alignment
# ---------------------------------------------------------------------------

_DECL_TYPE_COL  = 24   # Width of the type field  (e.g. "slot_t", "logic [PREG_W-1:0]")
_DECL_VAR_COL   = 28   # Width of the variable name field


def _declaration(block: BlockConfig) -> str:
    """Format a single variable declaration line."""
    type_field = f"{block.sv_type:<{_DECL_TYPE_COL}}"
    var_field  = f"{block.sv_var:<{_DECL_VAR_COL}}"
    dim        = f" [{block.sv_dim}]" if block.sv_dim else ""
    return f"  {type_field} {var_field}{dim};"


def _declarations_section(blocks: list[BlockConfig]) -> str:
    """Emit all variable declarations, grouped with a comment header."""
    lines = ["  // Grouped signal arrays — one entry per DUT instance"]
    for block in blocks:
        lines.append(f"  // {block.sv_comment}")
        lines.append(_declaration(block))
        lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# File header
# ---------------------------------------------------------------------------

_HEADER_TEMPLATE = """\
// =============================================================================
// grouper.sv — AUTO-GENERATED, DO NOT EDIT BY HAND
// Generated by grouper_gen on {date}
//
// This module groups flat Chisel-generated signals into typed SV structs and
// arrays for ergonomic access from verification environments.
//
// No outputs are driven — the grouped signals are accessed via hierarchical
// reference from any module that binds or instantiates BoomTile.
//
// Usage example:
//   soc1.grp.int_slots[3].uop.pdst
//
// Bind instantiation (in the testbench or miter):
//   bind BoomTile grouper grp (.*);
//
// Developed for SPT-BOOM — https://github.com/RPTU-EIS/SPT-BOOM
// =============================================================================

import boom_param_pkg::*;

module grouper #()
(
  input logic clock,
  input logic reset
);
"""

_FOOTER = "endmodule\n"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_sv_file(blocks: list[BlockConfig], indent: str = "  ") -> str:
    """
    Assemble the complete grouper.sv content from a list of BlockConfigs.

    Parameters
    ----------
    blocks : list[BlockConfig]
        All hardware blocks to include, in the order they will appear in the file.
    indent : str
        Base indentation string for the module body (default: two spaces).

    Returns
    -------
    str
        Full text of grouper.sv, ready to be written to disk.
    """
    sections: list[str] = []

    # File header + module signature
    sections.append(_HEADER_TEMPLATE.format(date=date.today().isoformat()))

    # Variable declarations
    sections.append(_declarations_section(blocks))
    sections.append("")

    # Assign blocks — one section per BlockConfig
    for block in blocks:
        sections.append(f"{indent}// {'=' * 74}")
        sections.append(f"{indent}// {block.sv_comment}")
        sections.append(f"{indent}// {'=' * 74}")
        sections.append(emit_block(block, indent=indent))

    sections.append(_FOOTER)
    return "\n".join(sections)
