"""
sv_file.py — Assembles the complete grouper.sv file.
"""

from datetime import date
from pathlib import Path

from pkg_parser import PkgInfo, load_pkg
from types_ import Block
from generator import emit_block

_DECL_TYPE_COL = 24
_DECL_VAR_COL  = 28


def _declaration(block: Block, pkg: PkgInfo) -> str:
    count     = pkg.resolve_count(block.count)
    type_f    = f"{block.type:<{_DECL_TYPE_COL}}"
    var_f     = f"{block.var:<{_DECL_VAR_COL}}"
    dim       = f" [{count - 1}:0]" if count > 1 else ""
    dim_note  = f"  // {block.count}" if isinstance(block.count, str) else ""
    var_col   = var_f if dim else var_f.rstrip()
    return f"  {type_f} {var_col}{dim};{dim_note}"


_HEADER = """\
// =============================================================================
// grouper.sv — AUTO-GENERATED, DO NOT EDIT BY HAND
// Generated by grouper_gen on {date}
//
// Groups flat Chisel-generated signals into typed SV structs for verification.
//
// Usage:  soc1.grp.int_slots[3].uop.pdst
// Bind:   bind BoomTile grouper grp (.*);
//
// Developed for SPT-BOOM — https://github.com/RPTU-EIS/SPT-BOOM
// =============================================================================

import boom_param_pkg::*;

module grouper #()
(
  input logic clock,
  input logic reset
);
"""

_FOOTER = "endmodule\n"


def build_sv_file(blocks: list[Block], pkg: PkgInfo, indent: str = "  ") -> str:
    sections = [_HEADER.format(date=date.today().isoformat())]

    # Declarations
    decl_lines = ["  // Grouped signal variables"]
    for b in blocks:
        decl_lines.append(f"  // {b.comment}")
        decl_lines.append(_declaration(b, pkg))
        decl_lines.append("")
    sections.append("\n".join(decl_lines))
    sections.append("")

    # Assignment blocks
    for b in blocks:
        sections.append(f"{indent}// {'=' * 74}")
        sections.append(f"{indent}// {b.comment}")
        sections.append(f"{indent}// {'=' * 74}")
        sections.append(emit_block(b, pkg, indent=indent))

    sections.append(_FOOTER)
    return "\n".join(sections)
